- name: Install Conky
  dnf:
    name: conky
    state: latest
- name: Ensure target directory is empty
  file:
        path: "{{ user_home_dir}}/{{ user_home_dir}}/{{ conf.xdghomeconfig }}/{{ conky.dir }}"
        state: absent
- name: Create target directory
  file:
    path: "{{ user_home_dir}}/{{ user_home_dir}}/{{ conf.xdghomeconfig }}/{{ conky.dir }}"
    state: directory
- name: Deploy configuration files
  copy:
    src: "{{ conf.conf_repo }}/{{ conky.dir }}/conky.conf"
    dest: "{{ user_home_dir}}/{{ user_home_dir}}/{{ conf.xdghomeconfig }}/{{ conky.dir }}"
