- name: Install Conky
  dnf:
    name: conky
    state: latest
- name: Ensure target directory is empty
  file:
        path: "{{ conf.xdghomeconfig }}/{{ conky.dir }}"
        state: absent
- name: Create target directory
  file:
    path: "{{ conf.xdghomeconfig }}/{{ conky.dir }}"
    state: directory
- name: Deploy configuration files
  copy:
    src: "{{ conf.source }}/{{ conky.dir }}/conky.conf"
    dest: "{{ conf.xdghomeconfig }}/{{ conky.dir }}"
