- name: Install Conky
  dnf:
    name: conky
    state: latest
  when: (applications['conky']['app'] is undefined and conf['actions']['app'] == yes) or
        applications['conky']['app'] == yes
- name: Ensure target directory is empty
  file:
        path: "{{ user_home_dir}}/{{ user_home_dir}}/{{ conf.xdghomeconfig }}/{{ conky.dir }}"
        state:  not present
  when:
    - (applications['conky']['delete_xdgdir_first'] is undefined and conf['actions']['delete_xdgdir_first'] == yes) or
      applications['conky']['delete_xdgdir_first'] == yes
    - (applications['conky']['config'] is undefined and conf['actions']['config'] == yes) or
      applications['conky']['config'] == yes
- name: Create target directory
  file:
    path: "{{ user.xdghomeconfig }}/{{ applications.conky.dir }}"
    state: directory
  when: (conky['config'] is undefined and conf['actions']['config'] == yes) or
        conky['config'] == yes
- name: Deploy configuration files
  copy:
    src: "{{ conf.conf_repo }}/{{ applications.conky.dir }}/conky.conf"
    dest: "{{ user.xdghomeconfig }}/{{ applications.conky.xdgdir }}"
  when: (applications['conky']['config'] is undefined and conf['actions']['config'] == yes) or
        applications['conky']['config'] == yes
