#+TITLE: Reve Workshop 

* Introduction
  :PROPERTIES:
  :ID:       061082f9-4977-4941-bca4-ee64c817e19d
  :END:
  This repository contains various description of projects past,
  present and future maybe.
* Repository structure
  :PROPERTIES:
  :ID:       6b5567b2-7bd2-4248-aeba-e740c9e6ad52
  :END:
** =ansible/=
   :PROPERTIES:
   :ID:       a721a1c3-da72-4052-b2c1-d0b4f137f46e
   :END:
   Document regarding various ansible projects, leading to
   repositories like =xyz.revecloud.re.ansible.reve-setup=, for
   example.
** =is.re=
   Description of a project to develop a software and a file format
   based on Common Lisp to manage an information system.
** =provisioning=
   Documents related to virtual environment provisioning in the
   =revecloud= infrastructure. Actually only proxmox compose the
   infrastructure.
* Author
  :PROPERTIES:
  :ID:       29dedef8-dfa5-4c47-97e5-b6332d1aaa15
  :END:

+ Roland Everaert

* Copyright
  :PROPERTIES:
  :ID:       1cde1676-e011-4df4-8f8a-b18e9d0d7fef
  :END:

Copyright (c) 2020 Roland Everaert
