#+TITLE: TODO

* Ansible
  :PROPERTIES:
  :ID:       fba2d23a-2680-4f62-a15f-8b7d080c5922
  :END:
** DONE Merge =deploy-config= and =setup-host=
   CLOSED: [2019-11-19 mar. 08:17]
   :PROPERTIES:
   :ID:       d3b52d34-1bbd-421d-bf10-4164e23a14b8
   :END:
   - State "DONE"       from "TODO"       [2019-11-19 mar. 08:17]
   Some applications need to be installed in the user environment and
   not during host set-up.

   It should be easier to manage everything from one ansible project
   instead of 2 or more for those tasks.

   In the new project, create 4 playbooks:
   - =host-setup.yml=, set-up a new host or ensure that a host has the
     minimum required for a REVE host.
   - =user-setup.yml=, set-up a new user or ensure that a user is set-up
     according to my standard.
   - =deploy-config.yml=, ensure the configuration is deployed for a
     user.
   - =sites.yml=, call the 3 other playbooks in this order:
     1. =host-setup.yml=
     2. =user-setup.yml=
     3. =deploy-config.yml=
** DONE Write a design document of some sort
   CLOSED: [2019-11-21 jeu. 08:20]
   :PROPERTIES:
   :ID:       58583e8a-e98f-4c8f-8562-56b38b99d0b4
   :END:
   - State "DONE"       from "TODO"       [2019-11-21 jeu. 08:20]
   The document should:
   - describe the variables used and how and where to populate them.
     - Idea: use =group_vars=, see actual implementation
       ([2019-11-05 mar.]) of =deploy-config= and =setup-host=.
   - define the intent of the playbooks.
** DONE Study how to deal with private data
   CLOSED: [2020-04-28 mar. 20:42]
   :PROPERTIES:
   :ID:       692c6cb5-a846-46e4-a9d6-b8168cd8af46
   :END:
   - Note taken on [2020-04-28 mar. 20:42] \\
     This is handled by issue [[https://github.com/REve-Workshop/xyz.revecloud.re.ansible.reve-setup/issues/2][Issue 2 - xyz.revecloud.re.ansible.reve-setup repository]].
   - Private repos
     - ansible_vault?
     - private playbooks?
   - Private files
     - ansible_vault?
     - private playbooks?
   - Data to modify/add/remove in standard files, with private data
     - ansible_vault?
     - private playbooks?
** DONE Study how to use the skeleton parameter of the =user= module
   CLOSED: [2020-04-28 mar. 20:54]
   :PROPERTIES:
   :ID:       cb42b36f-7101-4987-a575-134fe083c296
   :END:
   - Note taken on [2020-04-28 mar. 20:54] \\
     Follow up in [[https://github.com/REve-Workshop/xyz.revecloud.re.ansible.reve-setup/issues/1][Issue 1 - xyz.revecloud.re.ansible.reve-setup repository]].
   The skeleton parameter allows to use the skeleton feature of linux
   system. When using this feature, the content of =/etc/skel=, the
   skeleton directory, is used to populate the user's =$HOME= directory
   with an initial content.

   The skeleton directory should be populated during the host set-up
   phase.
** DONE Develop a playbook to install the UHK Agent
   CLOSED: [2020-04-28 mar. 21:08]
   :PROPERTIES:
   :ID:       a3bfc4bb-0044-4930-bb2c-f354d301ee86
   :END:
   - Note taken on [2020-04-28 mar. 21:08] \\
     Follow up at [[https://github.com/REve-Workshop/designer-desk/issues/9][Issues 9 - Designer Desk repository]].
   The UHK repository provides a file called =latest.yml=. Check with
   the vendor if it can be reliably used to retrieve the latest
   version of the agent and firmware.
** DONE Add a role to set-up =git_config=
   CLOSED: [2020-04-28 mar. 21:16]
   :PROPERTIES:
   :ID:       d593a5a3-0661-4e4a-b811-1f9bb1bbe104
   :END:
   - Note taken on [2020-04-28 mar. 21:16] \\
     Follow up in [[https://github.com/REve-Workshop/designer-desk/issues/11][Issues 11 - Designer Desk repository]].
