#+TITLE: TODO

* Ansible
  :PROPERTIES:
  :ID:       fba2d23a-2680-4f62-a15f-8b7d080c5922
  :END:
** TODO Merge =deploy-config= and =setup-host=
   :PROPERTIES:
   :ID:       d3b52d34-1bbd-421d-bf10-4164e23a14b8
   :END:
   Some applications need to be installed in the user environement and not during host setup.

   It should be easier to manage everything from one ansible project
   instead of 2 or more for those tasks.

   In the new project, create 4 playbooks:
   - =host-setup.yml=, setup a new host or ensure that a host has the minimum required for a REVE host.
   - =user-setup.yml=, setup a new user or ensure the a user is setup according to my standard.
   - =deploy-config.yml=, ensure the configuration is deployed for a user 
   - =sites.yml=, call the 3 other playbooks in this order:
     1. =host-setup.yml=
     2. =user-setup.yml=
     3. =deploy-config.yml=
** TODO Write a design document of some sort
   :PROPERTIES:
   :ID:       58583e8a-e98f-4c8f-8562-56b38b99d0b4
   :END:
   The document should describe the variables used and how and where to populate them.
   - Idea: use =group_vars=, see actual implementation
     ([2019-11-05 mar.]) of =deploy-config= and =setup-host=.
** TODO Study how to deal with private data
   :PROPERTIES:
   :ID:       692c6cb5-a846-46e4-a9d6-b8168cd8af46
   :END:
   - Private repos
   - Private files
   - Data to modify/add/remove in standard files (ansible_vault???), with private data
