- name: "Install {{ appl.key }} package."
  package:
    name: "{{ appl.key }}"
    state: latest
  when:
    - user['state'] == "all"
    - applic['uncommon'] is undefined
    - (applic['app'] is defined and applic['app'] == True) or
      (actions['app'] == True and applic['app'] is undefined)
- name: "Deploy {{ appl.key }} configuration"
  block:
    - name: Checkout lastest version of configuration repository
      git:
        repo: "{{ appl.value.repo }}"
        dest: "{{ conf.conf_repo }}/{{ appl.value.dir }}"
        state: latest
      when:
        - (applic['checkout'] is defined and applic['checkout'] == True) or
          (actions['checkout'] == True and applic['checkout'] is undefined)
        - (applic['config'] is defined and applic['config'] == True) or
          (actions['config'] == True and applic['config'] is undefined)
    - name: "Delete old configuration directory"
      file:
        path: "{{ user.xdghomeconfig }}/{{ appl.value.xdgdir }}"
        state: absent
      when:
        - (applic['config'] is defined and applic['config'] == True) or
          (actions['config'] == True and applic['config'] is undefined)
        - (applic['delete_xdgdir_first'] is defined and applic['delete_xdgdir_first'] == True) or
          (actions['delete_xdgdir_first'] == True and applic['delete_xdgdir_first'] is undefined)
    - name: "Create new configuration directory"
      file:
        path: "{{ user.xdghomeconfig }}/{{ appl.value.xdgdir }}"
        state: directory
      when:
        - (applic['config'] is defined and applic['config'] == True) or
          (actions['config'] == True and applic['config'] is undefined)
    - name: "Deploy new configuration resources"
      copy:
        src: "{{ conf.conf_repo }}/{{ applic.dir }}/{{ item }}"
        dest: "{{ user.xdghomeconfig }}/{{ appl.value.xdgdir }}"
      loop: "{{ appl.value.files }}"
      when: (applic['config'] is defined and applic['config'] == True) or
            (actions['config'] == True and applic['config'] is undefined)
  when:
    - user['state'] == "configonly" or user['state'] == "all"
