- name: Enable Alacritty Copr repository
  yum_repository:
    name: copr:copr.fedorainfracloud.org:pschyska:alacritty
    description: Copr repo for alacritty owned by pschyska
    baseurl: https://copr-be.cloud.fedoraproject.org/results/pschyska/alacritty/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/pschyska/alacritty/pubkey.gpg
  when: alacritty['app'] == True
- name: Install Alacritty
  dnf:
    name: alacritty
    state: latest
  when: alacritty['app'] == True
- name: Ensure Alacritty Configuration repository is present and the latest
  git:
    repo: "{{ alacritty.repo }}"
    dest: "{{ conf.conf_repo }}/{{ alacritty.dir }}"
    state: latest
  notify:
    - "Delete directory {{ user.xdghomeconfig }}/alacritty"
    - "Deploy {{ alacritty.dir }} configuration files"
  when: alacritty['config'] == True
