- name: Ensure ZSH Configuration repository is present and the latest
  git:
    repo: "{{ zsh.repo }}"
    dest: "{{ conf.conf_repo }}/{{ zsh.dir }}"
    state: latest
  notify:
    - "Delete directory {{ user.xdghomeconfig }}/zsh"
    - Deploy .zshrc
    - "Deploy {{ zsh.dir }}/zsh"
  when: zsh['config'] == True
