#+TITLE: User configuration deployment ansible playbooks

* Purpose
  :PROPERTIES:
  :ID:       e07f89dd-c891-46cf-860e-3ee3925f373f
  :END:
  These playbooks are to be used whenever some of my configuration has
  changed and I want to propagate it on all my machines.

  There are 2 playbooks:
  - workstations.yml
  - servers.yml
* Usage
  :PROPERTIES:
  :ID:       b4822be3-3f89-42d2-ae6e-230f9e0a1be6
  :END:
  #+begin_example
    ansible-playbook -i <inventory> workstation.yml|servers.yml -e '@<user-config.yml>' [OPTIONS]
  #+end_example

  - =<inventory>=, an inventory file listing machines impacted by the playbbok
  - =workstation.yml=, playbook for deploying configuration on linux workstations
  - =servers.yml=, playbook for deploying configuration on linux servers
  - =<user-config.yml>=, of YAML file containing the variables to use
    by the playbook, beside the default ones.
* Playbooks
  :PROPERTIES:
  :ID:       8e607928-2663-4e65-9e6c-21d4bd0d74a6
  :END:

  The difference between the playbooks is related to the list of roles
  they are executing and the group of hosts they are targeting.

  The targeted hosts are expected to be linux OS.
** Configuration deployment for servers
   :PROPERTIES:
   :ID:       b8dafad9-98c4-4252-84ee-9e84a722481a
   :END:
  Use the playbook =servers.yml= is this case.

  It will act on hosts in the group =servers= of the inventory
  file. Has no graphical servers are deployed on my linux servers,
  there is less configuration element to deploy, for exemple, stumpwm
  or end-user applications like surfraw are not part of the playbook
  tasks.
** Configuration deployment for Workstations
   :PROPERTIES:
   :ID:       0820fdad-9682-4986-84b9-7f9279b62740
   :END:
   Use the playbook =workstations.yml= is this case.

   This is the biggest of the playbook. It will execute for all hosts
   in the =workstations= group.
** Deciding which task to perform
   :PROPERTIES:
   :ID:       e321e203-7d01-4d48-b381-2e473d8cfc21
   :END:
   With the file =<user-config.yml>=, it is possible to limit the
   tasks of the playbooks.
   
   The playbooks perform the following steps:
   1. Update the local copy of the repository containing the configuration.
   2. Create the user and its basic directory structure, if a new user is requested
   3. For each application configured, execute its role

   For each application's configuration, an ansible role is
   defined. Each role perform the following tasks:
   1. Install the software related to the configuration, if requested
   2. If deployment of the configuration is requested:
      1. Clean the user directory of any existing configuration for the application
      2. Deploy the last version of the configuration available
