---
- hosts: workstations
  connection: local
  gather_facts: False
  roles:
    - zsh-config
    - config-xdg
    - dunst
    - stumpwm-config
    - alacritty
    - mpd
    - conky
    - emacs
    - neofetch
    - nitrogen
    - ranger
    - surfraw
    - uhk-agent
    - variety
    - tmux
