---
- hosts: workstations
  gather_facts: False
  tasks:
    - name: Create user environement
      include_role:
        name: config-xdg
      when: user['state'] != 'None'
    - name: Deploy ZSH configuration
      include_role:
        name: zsh-config
      become: true
      become_user: "{{ user.name }}"
      when:
        - user['state'] == "configonly" or user['state'] == "all"
        - applications['zsh']['uncommon'] is defined
        - (conf['actions']['config'] == True and applications['zsh']['config'] is undefined) or
          (applications['zsh']['config'] is defined and applications['zsh']['config'] == True)
    - name: Deploy TMux configuration
      include_role:
        name: tmux
      become: true
      become_user: "{{ user.name }}"
      when:
        - user['state'] == "configonly" or user['state'] == "all"
        - applications['tmux']['uncommon'] is defined
        - (conf['actions']['config'] == True and applications['tmux']['config'] is undefined) or
          (applications['tmux']['config'] is defined and applications['tmux']['config'] == True)
    - name: Deploy Emacs configuration
      include_role:
        name: emacs
      become: true
      become_user: "{{ user.name }}"
      when:
        - user['state'] == "configonly" or user['state'] == "all"
        - applications['emacs']['uncommon'] is defined
        - (conf['actions']['config'] == True and applications['emacs']['config'] is undefined) or
          (applications['emacs']['config'] is defined and applications['emacs']['config'] == True)
    - name: Deploy StumpWM configuration
      include_role:
        name: stumpwm-config
      become: true
      become_user: "{{ user.name }}"
      when:
        - user['state'] == "configonly" or user['state'] == "all"
        - applications['stumpwm']['uncommon'] is defined
        - (conf['actions']['config'] == True and applications['stumpwm']['config'] is undefined) or
          (applications['stumpwm']['config'] is defined and applications['stumpwm']['config'] == True)
    - name: Deploy Alacritty configuration
      include_role:
        name: alacritty
      become: true
      become_user: "{{ user.name }}"
      when:
        - user['state'] == "configonly" or user['state'] == "all"
        - applications['alacritty']['uncommon'] is defined
        - (conf['actions']['config'] == True and applications['alacritty']['config'] is undefined) or
          (applications['alacritty']['config'] is defined and applications['alacritty']['config'] == True)
    - name: Deploy regular applications configuration
      include_role:
        name: common
      loop: "{{ applications|dict2items }}"
      loop_control:
        loop_var: appl
      when:
        - user['state'] == "configonly" or user['state'] == "all"
        - appl['value']['uncommon'] is undefined
        - ((conf['actions']['app'] == True and appl['value']['app'] is undefined) or (appl['value']['app'] is defined and appl['value']['app'] == True)) or ((conf['actions']['config'] == True and appl['value']['config'] is undefined) or (appl['value']['config'] is defined and appl['value']['config'] == True))
