---
- hosts: workstations
  gather_facts: False
  roles:
    - config-xdg
    # - update-local-config-repo
    - zsh-config
    # - tmux
    # - emacs
    # - dunst
    # - stumpwm-config
    # - alacritty
    # - mpd
    # - conky
    # - neofetch
    # - nitrogen
    # - ranger
    # - surfraw
    # - uhk-agent
    # - variety
