---
- hosts: workstations
  gather_facts: False
  tasks:
    - name: Create user environement
      include_role:
        name: config-xdg
      when: user['state'] != 'None'
    # - zsh-config
    # - tmux
    # - emacs
    # - stumpwm-config
    # - alacritty
    - name: Deploy regular applications
      include_role:
        name: common
      loop: "{{ applications|dict2items }}"
      loop_control:
        loop_var: appl
      when: appl['value']['uncommon'] is undefined
