- name: Delete current configuration directory
  file:
    path: "{{ conf.xdghomeconfig }}/{{ item.value.xdgdir }}"
    state: absent
  loop: "{{ applications|dict2items }}"
  when: item['value']['uncommon'] is absent and ((conf['actions']['delete_xdgdir_first'] == yes and item['value']['delete_xdgdir_first'] is absent) or item['value']['delete_xdgdir_first'] == yes)
- name: Deploy configuration directory
  copy:
    src: "{{ conf.src }}/{{ item.value.dir }}"
    dest: "{{ user.xdghomeconfig }}/{{ item.value.xdgdir }}"
  loop: "{{ applications|dict2items }}"
  when: item['value']['uncommon'] is absent
