- name: Create user home
  block:
    - name: Create user
      user:
        name: "{{ user.name }}"
        comment: "{{ user.comment }}"
        create_home: True
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        state: present
    - name: Create user directories
      file:
        path: "{{ user.home }}/{{ item.value }}"
        state: directory
        loop: "{{ xdg|dict2items }}"
    - name: Create extra user directories
      file:
        path: "{{ user.home }}/{{ item }}"
        state: directory
        loop: "{{ extra }}"
  when: user['state'] == "create" or user['state'] == "all"
- name: Setup XDG environement
  block:
    - name: Create XDG configuration directory
      file:
        path: "{{ user.xdghomeconfig }}"
        state: directory
    - name: Deploy XDG configuration file
      template:
        src: user-dirs.dirs.j2
        dest: "{{ user.xdghomeconfig }}/user-dirs.dirs"
  when: user['state'] == "configonly" or user['state'] == "all"
